id: P003032
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:35:29.856697
source_metadata:
  id: bdr:W1KG662
  title: བོད་དབྱིན་རྒྱ་གསུམ་གྱི་སྨན་ཁང་ཉེར་མཁོའི་བརྡ་སྤྲོད
  author: ''
  volumes:
    85d7f8740fe54222a8fa96fd797d337c:
      image_group_id: I1KG1223
      title: ''
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
