id: I62C9A31A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:10:03+00:00'
last_modified: '2022-06-07T17:05:56.525740+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG662
  title: བོད་དབྱིན་རྒྱ་གསུམ་གྱི་སྨན་ཁང་ཉེར་མཁོའི་བརྡ་སྤྲོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    161D:
      image_group_id: I1KG1223
      title: ''
      total_pages: 244
      order: 1
      base_file: 161D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
